<div class="anchor" id="E"> </div>
<div class="container pt-5">
    <h4 class="text-center">E</h4>
</div>
<ul class="list-group">
    <li class="list-group-item"><strong>Effective Gross Income</strong><br>Gross income of a building if fully rented, less an allowance for estimated vacancies.</li>
    <li class="list-group-item"><strong>Engineering Report</strong><br>Report generated by an architect or engineer describing the current physical condition of the property and its major building systems, i.e., HVAC, parking lot, roof, etc. The report also determines an amount for calculating replacement reserves, if needed.</li>
    <li class="list-group-item"><strong>Entitlements</strong><br>A right to benefits specified especially by law or contract.</li>
    <li class="list-group-item"><strong>Entity</strong><br>Either an LLC, a corporation, a sole proprietorship, or a partnership; not an individual.</li>
    <li class="list-group-item"><strong>Environmental Report</strong><br>Report generated by qualified environmental firms to determine potential environmental hazards in a building’s region or within the building itself.</li>
    <li class="list-group-item"><strong>Environmental Risk</strong><br>Risk of loss of collateral value and of lender liability due to the presence of hazardous materials, such as asbestos, PCB’s, radon, or leaking underground storage tanks (lusts) on a property.</li>
    <li class="list-group-item"><strong>Escrow</strong><br>An impartial third party that acts on behalf of either seller/buyer or borrower/lender in carrying out the principals’ instructions through to an eventual “closing”. Escrow acts as the custodian for the documents and funds involved – and makes disbursements, delivers documents and effects the consequential changes to the title record of the subject property.</li>
    <li class="list-group-item"><strong>Equity</strong><br>The difference between market value and the amount you owe on a property. Your equity can increase over time if property value increases or your loan balance is paid down.</li>
    <li class="list-group-item"><strong>Eurodollar</strong><br>U.S. dollar-denominated deposits at commercial banks outside of the united states.</li>
    <li class="list-group-item"><strong>Exit Strategy</strong><br>How the borrower plans to pay off the loan, as well as turn a profit. Having a clear exit strategy is an important part of developing your overall plan for the project which will help determine the best type of financing for the deal (i.e. refinance, sell, hold).</li>
  </ul>